using System.Collections.Generic;
using ArenaShooter.Core;
using UnityEngine;
using UnityEngine.Rendering;

namespace ArenaShooter.Gameplay
{
    /// <summary>
    /// Loads the Space Grunts 3D models (generated by Tools/ModelGen into Resources/Models/*.bytes)
    /// and instantiates them. Meshes are built once and shared; materials resolve by name so
    /// team colors, glass and glows use the build-safe materials from <see cref="GrayBox"/>.
    /// Models are visual only: no colliders.
    /// </summary>
    public static class ModelLibrary
    {
        private sealed class Entry
        {
            public ModelData Data;
            public Mesh[] Meshes;
            public Bounds Bounds;
        }

        private static readonly Dictionary<string, Entry> Cache = new Dictionary<string, Entry>();
        private static readonly HashSet<string> Missing = new HashSet<string>();

        public static readonly Color HelmetGlass = new Color(0.75f, 0.95f, 1f, 0.28f);

        public static bool Has(string name) => Load(name) != null;

        /// <summary>Model-space bounds (all parts), or an empty box if the model is missing.</summary>
        public static Bounds GetBounds(string name) => Load(name)?.Bounds ?? new Bounds(Vector3.zero, Vector3.one);

        /// <summary>
        /// Instantiates the model under <paramref name="parent"/> (local transform identity). Each part
        /// becomes a child named after it, positioned at its pivot; markers become empty children
        /// named "Marker_&lt;name&gt;". Returns null if the model file is missing.
        /// </summary>
        public static Transform Spawn(string name, Transform parent, Color team, Color? tint = null)
        {
            var entry = Load(name);
            if (entry == null) return null;

            var root = new GameObject("Model_" + name).transform;
            root.SetParent(parent, false);

            for (int i = 0; i < entry.Data.Parts.Count; i++)
            {
                var part = entry.Data.Parts[i];
                var go = new GameObject(part.Name);
                go.transform.SetParent(root, false);
                go.transform.localPosition = ToVector(part.Pivot);
                go.AddComponent<MeshFilter>().sharedMesh = entry.Meshes[i];
                var renderer = go.AddComponent<MeshRenderer>();
                var materials = new Material[part.Submeshes.Count];
                bool glowOnly = true;
                for (int s = 0; s < materials.Length; s++)
                {
                    string m = part.Submeshes[s].Material;
                    materials[s] = Resolve(m, team, tint ?? team);
                    glowOnly &= m.StartsWith("Glow");
                }
                renderer.sharedMaterials = materials;
                if (glowOnly) renderer.shadowCastingMode = ShadowCastingMode.Off;
            }

            foreach (var marker in entry.Data.Markers)
            {
                var m = new GameObject("Marker_" + marker.Key).transform;
                m.SetParent(root, false);
                m.localPosition = ToVector(marker.Value);
            }
            return root;
        }

        /// <summary>
        /// Spawns a model stretched to fill an axis-aligned box (used to dress invisible colliders,
        /// e.g. rocks and crates): the model's bounds are fitted to <paramref name="size"/> and
        /// centered on <paramref name="center"/>, then rotated.
        /// </summary>
        public static Transform SpawnFitted(string name, Transform parent, Vector3 center, Vector3 size, Quaternion rotation, Color team, Color? tint = null, float inflate = 1.06f)
        {
            var pivot = new GameObject("Fitted_" + name).transform;
            pivot.SetParent(parent, false);
            pivot.SetPositionAndRotation(center, rotation);
            var model = Spawn(name, pivot, team, tint);
            if (model == null) return pivot;

            Bounds b = GetBounds(name);
            var scale = new Vector3(size.x / Mathf.Max(0.001f, b.size.x), size.y / Mathf.Max(0.001f, b.size.y), size.z / Mathf.Max(0.001f, b.size.z)) * inflate;
            model.localScale = scale;
            model.localPosition = -Vector3.Scale(b.center, scale);
            return pivot;
        }

        public static Material Resolve(string material, Color team, Color tint)
        {
            switch (material)
            {
                case "Team": return GrayBox.Mat(team);
                case "TeamDark": return GrayBox.Mat(Color.Lerp(team, Color.black, 0.28f));
                case "TeamLight": return GrayBox.Mat(Color.Lerp(team, Color.white, 0.4f));
                case "GlowTeam": return GrayBox.Glow(team);
                case "Glass": return GrayBox.Glass(HelmetGlass);
                case "Tint": return GrayBox.Mat(tint);
            }
            if (material.StartsWith("Color:")) return GrayBox.Mat(ParseHex(material.Substring(6)));
            if (material.StartsWith("Glow:")) return GrayBox.Glow(ParseHex(material.Substring(5)));
            return GrayBox.Mat(Color.magenta);
        }

        private static Entry Load(string name)
        {
            if (Cache.TryGetValue(name, out var cached)) return cached;
            if (Missing.Contains(name)) return null;

            var asset = Resources.Load<TextAsset>("Models/" + name);
            if (asset == null)
            {
                Debug.LogWarning($"Model '{name}' not found in Resources/Models; using fallback shapes.");
                Missing.Add(name);
                return null;
            }

            var data = ModelFormat.Parse(asset.bytes);
            var entry = new Entry { Data = data, Meshes = new Mesh[data.Parts.Count] };
            for (int i = 0; i < data.Parts.Count; i++) entry.Meshes[i] = BuildMesh(name, data.Parts[i]);
            data.GetBounds(out var min, out var max);
            entry.Bounds = new Bounds();
            entry.Bounds.SetMinMax(ToVector(min), ToVector(max));
            Cache[name] = entry;
            return entry;
        }

        private static Mesh BuildMesh(string model, ModelPart part)
        {
            int vc = part.VertexCount;
            var vertices = new Vector3[vc];
            var normals = new Vector3[vc];
            for (int v = 0; v < vc; v++)
            {
                vertices[v] = new Vector3(part.Positions[v * 3], part.Positions[v * 3 + 1], part.Positions[v * 3 + 2]);
                normals[v] = new Vector3(part.Normals[v * 3], part.Normals[v * 3 + 1], part.Normals[v * 3 + 2]);
            }

            var mesh = new Mesh { name = model + "_" + part.Name };
            if (vc > 65000) mesh.indexFormat = IndexFormat.UInt32;
            mesh.vertices = vertices;
            mesh.normals = normals;
            mesh.subMeshCount = part.Submeshes.Count;
            for (int s = 0; s < part.Submeshes.Count; s++) mesh.SetTriangles(part.Submeshes[s].Indices, s);
            mesh.RecalculateBounds();
            return mesh;
        }

        private static Vector3 ToVector(float[] v) => new Vector3(v[0], v[1], v[2]);

        private static Color ParseHex(string hex)
        {
            return ColorUtility.TryParseHtmlString("#" + hex, out var c) ? c : Color.magenta;
        }
    }
}
